### ISSUE TITLE
Examples using old ApproxFun package structure

### ISSUE THREAD

**Issue by TSGut** [JuliaApproximation/MultivariateOrthogonalPolynomials.jl#6]
In some places the package still attempts to import functions which have been moved from ApproxFun to ApproxFunBase and so on. A few examples I quickly found are in 

https://github.com/JuliaApproximation/MultivariateOrthogonalPolynomials.jl/blob/038850f57d2fd1aa9e50f460e2b391fcb9b9b652/examples/L-shaped%20Laplace.jl

and

https://github.com/JuliaApproximation/MultivariateOrthogonalPolynomials.jl/blob/ea84cf3f15a18f2eccbb510938bc1ff45beee423/examples/triangleexamples.jl

That means even a consistent fresh install won't be able to run them as it is and it will also throw warnings upon compiling the package. We should probably go through and update them to the new ApproxFun structure.

**Comment by dlfivefifty** [comment]
Yes. This can be done once everything is up to date with FastTransforms.jl v0.8

**Comment by dlfivefifty** [comment]
PS You should update to Julia v1.3 as this will happen

**Comment by TSGut** [comment]
Seems like the workaround for the triangle at the bottom of Triangle.jl still attempts to import old structures: https://github.com/JuliaApproximation/MultivariateOrthogonalPolynomials.jl/blob/2b4244fac5201c6adba4acf9913b7c8eddebbab0/src/Triangle/Triangle.jl

I think this might be all that is left, though.

**Comment by dlfivefifty** [comment]
If you click on the line number on the left and choose "Copy permalink" that will show which line you are referring to

**Comment by TSGut** [comment]
Useful. It's right at the bottom: https://github.com/JuliaApproximation/MultivariateOrthogonalPolynomials.jl/blob/2b4244fac5201c6adba4acf9913b7c8eddebbab0/src/Triangle/Triangle.jl#L1375

**Comment by dlfivefifty** [comment]
Changing it to ` ApproxFunBase ` or ` BlockBandedMatrices ` should fix it
