### ISSUE TITLE
Encountering BoundsErrors with ClenshawMultiplication operators

### ISSUE THREAD

**Issue by TSGut** [JuliaApproximation/MultivariateOrthogonalPolynomials.jl#7]
Running simple things like this in fresh install:
```
T = JacobiTriangle()
(x,y) = Fun(identity, T)
Multiplication(y, T)
```
returns 

> BoundsError: attempt to access 1×2 BandedMatrix{Float64,Array{Float64,2},Base.OneTo{Int64}} at index [2, 1]

The error seems to originate somewhere in the Clenshaw algorithm step.

Would like to know if this reproduces for other people as well. Was this bug introduced during the LazyArrays version support change? I'm running all packages at the highest consistent version, i.e. LazyArrays v0.10.0 etc.. 

My older working instances run the above code without problems.

**Comment by dlfivefifty** [comment]
This is where strict upper bounds / Manifests are useful. Unfortunately it’s probably too late now to figure out the “right” package versions. 

I’ll try to get to fixing this this week

**Comment by dlfivefifty** [comment]
I suppose a good idea is to work in projects under Github. Then one can go back and look at the historical Manifest.toml.

In fact, that might work here: I believe I was using our shared Github as a project so there should be a historical Manifest.toml in git history.

**Comment by TSGut** [comment]
The issue I described in this seems to be fixed by #8 as well. A fresh install in Julia 1.3 at highest compatible package versions now no longer errors when generating Multiplication operators. However, it seems the Multiplication operators are now computed in a dense way instead of a banded / block banded way? For example, running 
```
T = JacobiTriangle()
(x,y) = Fun(identity, T)
Multiplication(y, T)[1:100,1:100]
```
produces a RaggedMatrix with dense 0s instead of the neat banded matrix one would expect, leading to slow code in high order cases. Though I think that might be a separate issue now?

**Comment by dlfivefifty** [comment]
I’m pretty sure you need to index by blocks to get it as a ` BandedBlockBandedMatrix `: ` A[Block.(1:100), Block.(1:100)] `

**Comment by TSGut** [comment]
Cool, I think it used to work without block indexing as well before but this works nicely. I'll close this then, seems all fixed.
