### ISSUE TITLE
Dependency with HOPs reversed?

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaApproximation/MultivariateOrthogonalPolynomials.jl#79]
I'm struggling to understand the dependency order between HarmonicOrthogonalPolynomials and MultivariateOrthogonalPolynomials. To me, a harmonic OP is an OP before it's harmonic, and since harmonicity is trivial for univariate polynomials that means multivariate orthogonality among polynomials is more fundamental an idea.

Maybe this is just a temporary defect in the way the repositories evolved?

**Comment by dlfivefifty** [comment]
It's because OPs on the disk are defined in terms of spherical harmonics

**Comment by MikaelSlevinsky** [comment]
Do they really need another repository or are they best distinguished by a trait, isharmonic?

**Comment by dlfivefifty** [comment]
Nothing needs another repository, we could just have one giant repository for everything. It’s just a bad idea 👎
